import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import CookieBanner from "@/components/cookies/CookieBanner";
import {LanguageProvider} from "@/contexts/LanguageContext";
import { getServerTranslations, getServerLanguage } from '@/../lib/translations-server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anglokom - Profesjonalne Szkolenia językowe dla firm i Tłumaczenia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const language = await getServerLanguage();
    const initialTranslations = await getServerTranslations(language);
  return (
    <html lang={language}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <LanguageProvider
              initialTranslations={initialTranslations}
              initialLanguage={language as 'pl' | 'en' | 'de'}
          >
            {children}
          </LanguageProvider>
          <CookieBanner />
      </body>
    </html>
  );
}
